### ISSUE TITLE
Something

### ISSUE THREAD

**Issue by DarkerInkO** [Bocon-Hosting/BoconHosting-Master#3]
:3 On a new laptop atm and since my emails/discord email has 2fa can't login atm but my new laptop its pretty good :) i should be back tmr 

better then my old laptop
![image](https://user-images.githubusercontent.com/86142669/122632920-917ec280-d08a-11eb-8cb9-0b452008453b.png)

**Comment by DarkerInkO** [comment]
![image](https://user-images.githubusercontent.com/86142669/122633132-c8090d00-d08b-11eb-929c-ae715430217a.png)

it can run minecraft shaders pretty well ||don't mind the timer, waiting until I get home to buy mc||

**Comment by Xcyth** [comment]
i see

**Comment by DarkerInkO** [comment]
*well time to wait 12h to go home*

**Comment by Xcyth** [comment]
> ![image](https://user-images.githubusercontent.com/86142669/122633132-c8090d00-d08b-11eb-929c-ae715430217a.png)
> 
> it can run minecraft shaders pretty well ||don't mind the timer, waiting until I get home to buy mc||

but its 21fps lmao

**Comment by DarkerInkO** [comment]
> > ![image](https://user-images.githubusercontent.com/86142669/122633132-c8090d00-d08b-11eb-929c-ae715430217a.png)
> > it can run minecraft shaders pretty well ||don't mind the timer, waiting until I get home to buy mc||
> 
> but its 21fps lmao

Well yea but 10000% better once I get all my settings right, that was just with basic settings

**Comment by Xcyth** [comment]
> > > ![image](https://user-images.githubusercontent.com/86142669/122633132-c8090d00-d08b-11eb-929c-ae715430217a.png)
> > > it can run minecraft shaders pretty well ||don't mind the timer, waiting until I get home to buy mc||
> > 
> > 
> > but its 21fps lmao
> 
> Well yea but 10000% better once I get all my settings right, that was just with basic settings

i see

**Comment by DarkerInkO** [comment]
![image](https://user-images.githubusercontent.com/86142669/122633753-00f6b100-d08f-11eb-957a-cc38cc5c4b57.png)

this was a few hours ago

**Comment by DarkerInkO** [comment]
***I will be back tmr, Idk when but should be at noon for me***

**Comment by Darker-Ink** [comment]
I'm Home :D
